// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1
)
RETURNING id, created_at, updated_at, email
`

func (q *Queries) CreateUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const resetUsers = `-- name: ResetUsers :one
WITH deleted AS (
    DELETE FROM users
    RETURNING id, created_at, updated_at, email
)
SELECT COUNT(*) AS deleted_count
FROM deleted
`

func (q *Queries) ResetUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, resetUsers)
	var deleted_count int64
	err := row.Scan(&deleted_count)
	return deleted_count, err
}
